watch_stylesheet: true
watch_config: true
debug: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true 
      acrylic: true 
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "home", 
          "launchpad",
          "notes",
          "media", 
          "active_window"
      ]
      center: [
          "clock",
        ]
      right: [
          "systray",
          "device-stats",
          "network",
          "volume",
          "battery",
          "language",
          "notifications",
          "power_menu"
      ]
widgets:
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\udb82\udd0c"
        delete: "\ueab8"
        copy: "\uebcc"
      callbacks:
        on_left: "toggle_menu"
        on_right: "toggle_label"
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads"}
        - { title: "Documents", path: "~\\Documents"}
        - { title: "YASB Config", path: "~\\.config\\yasb\\config.yaml"}
        - { title: "YASB Styling", path: "~\\.config\\yasb\\styles.css"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "#7aa2f7"
      alignment: "left"
      menu_labels:
        
      offset_left: 4
      offset_top: 0
  launchpad:
    type: "yasb.launchpad.LaunchpadWidget"
    options:
      label: "<span>\uf40e</span> Shortcuts"
      search_placeholder: "Search apps..."
      app_icon_size: 48
      window:
        fullscreen: false
        width: 800
        height: 600
        overlay_block: true
      window_style:
        enable_blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
      window_animation:
        fade_in_duration: 200
        fade_out_duration: 200
      callbacks:
        on_left: "toggle_launchpad"
      app_title_shadow:
        enabled: true
        color: "#00000090"
        offset: [1, 1]
        radius: 2
      app_icon_shadow:
        enabled: true
        color: "#00000090"
        offset: [0, 2]
        radius: 8
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "\uf001 {title} - {artist}"
      label_alt: "\uf001 {title}"
      max_field_size:
        label: 15
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: false
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      media_menu:
        border_color: '#7aa2f7'
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      callbacks:
        on_left: "toggle_media_menu"
        on_right: "toggle_label"
  media_menu:
    thumbnail_size: 3
    thumbnail_corner_radius: 12
    offset_left: 12
    blur: true
    round_corners: true
    round_corners_type: "normal"
    border_color: "#7aa2f7"
    alignment: "right"
    direction: "down"
    offset_top: 6
    max_title_size: 80
    max_artist_size: 24
    show_source: true
    show_duration_slider: false
    options:
      media_menu:
        border_color: '#7aa2f7'
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf47d"
      label_expanded: "\uf460"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      tooltip: true
  device-stats:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "device-stats"
      widgets: [
        "memory",
        "cpu",
        "disk",
      ]
      container_padding:
        top: 0
        left: 2
        bottom: 0
        right: 2
  network:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "network"
      widgets: [
        "wifi",
        "traffic",
      ]
      container_padding:
        left: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]:.0f}%"
      label_alt: "<span>\uf4bc</span> {info[percent][total]:.0f}%"
      update_interval: 2000
      callbacks:
        on_right: "toggle_label"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span> Drives"
      label_alt: "<span>\uf473</span>"
      group_label:
        volume_labels: ["C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
        show_label_name: false 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: '#7aa2f7'
        alignment: 'center'
        offset_top: 0
      callbacks:
        on_left: "toggle_group"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "<span>\uf476</span> {count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "exe='{win[process][name]}' | hwnd=#{win[hwnd]}"
      label_no_window: "No Window Detected"
      label_icon: true
      label_icon_size: 14
      max_length: 15
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span>{%I:%M:%S %p}"
      label_alt: "<span>\uf017</span>{%A, %B %d, %Y | %H%M.%S}"
      locale: "en_AU"
      timezones: []
      calendar:
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        offset_top: 0
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      ethernet_label: "<span>{wifi_icon}</span> {wifi_name}"
      ethernet_icon: "\uf108"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network-wifi"
        on_middle: "do_nothing"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
      ]
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      mute_text: "Muted"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
      callbacks:
        on_right: "toggle_mute"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      #hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}" 
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        lock: ["\uea75", "Lock"]
        cancel: ["","Cancel"]
        
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\udb80\udf0c</span> {lang[country_code]}"
      label_alt: "<span>\udb80\udf0c</span> {lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
